get  http://localhost:8000/references
Content-Type: application/json

###
post  http://localhost:8000/references
Content-Type: application/json


{  
  "appellation": "Chinon",
  "terroir": "",
  "label": "AOC-AOP",
  "color": "Rouge",
  "variety": "Chenin",
  "type": "Sec",
  "category": "Région 1",
  "reward": "",
  "precision": "2005 est une année exceptionnelle",
  "year": 2015,
  "price": "30"
}

###
put  http://localhost:8000/references/10
Content-Type: application/json


{   
  "terroir": "Lorem ipsum",
  "year": 2005
}

###
delete  http://localhost:8000/references/3
Content-Type: application/json

###
get  http://localhost:8000/prices?type=Sec&appellation=Chinon&year=2015&reward=Récompense+N°2
