GET http://localhost:8000/users

###
POST http://localhost:8000/users
Content-type: application/json

{
    "email": "abc@mail.com",
    "password": "123456"
}

###
POST http://localhost:8000/login
Content-type: application/json

{
    "email": "abc@mail.com",
    "password": "123456"
}

###
GET http://localhost:8000/users/1/bottles

###
POST http://localhost:8000/users/1/bottles
Content-type: application/json

{
    "type": "Sec",
    "appellation": "Chinon",
    "year": 2000,
    "reward": "",
    "reference_Id": 1
}

###
PUT http://localhost:8000/users/1/bottles/7
Content-type: application/json

{
    "name": "tested 4"
}

###
DELETE http://localhost:8000/users/1/bottles/6

